-- Seed data: categories + placeholder catalog (replace imagery with real photography before launch)
insert into categories (slug, name, description) values
  ('earrings', 'Earrings', 'Hoops, studs, and drops in PVD gold.'),
  ('rings', 'Rings', 'Signets, bands, and stone rings, true to size.'),
  ('bracelets', 'Bracelets', 'Chains, bangles, and cuffs built to hold up.'),
  ('necklaces', 'Necklaces', 'Chains and pendants for everyday layering.')
on conflict (slug) do nothing;

insert into products (sku, name, slug, category_id, price, compare_at_price, description, plating_spec, material_spec, images, stock_count, is_new, ring_size_range) values
  ('1720-EAR-001', 'Sadaf Hoop Earrings', 'sadaf-hoop-earrings', (select id from categories where slug = 'earrings'), 3200, null, 'Chunky retro hoops with a brushed finish. Everyday wear, hypoallergenic base.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/sadaf-hoop-earrings-1.svg','/products/sadaf-hoop-earrings-2.svg'], 4, true, null),
  ('1720-EAR-002', 'Noor Drop Earrings', 'noor-drop-earrings', (select id from categories where slug = 'earrings'), 3600, null, 'Teardrop silhouette with a warm, retro-gold tone. Secure butterfly backs.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/noor-drop-earrings-1.svg','/products/noor-drop-earrings-2.svg'], 11, true, null),
  ('1720-EAR-003', 'Meher Stud Earrings', 'meher-stud-earrings', (select id from categories where slug = 'earrings'), 2800, null, 'Cubic zirconia studs set in a low-profile PVD gold setting. Easy to layer.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/meher-stud-earrings-1.svg','/products/meher-stud-earrings-2.svg'], 18, false, null),
  ('1720-EAR-004', 'Zara Chain Earrings', 'zara-chain-earrings', (select id from categories where slug = 'earrings'), 3400, null, 'Fine curb-chain drops that catch the light without being loud.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/zara-chain-earrings-1.svg','/products/zara-chain-earrings-2.svg'], 5, false, null),
  ('1720-EAR-005', 'Laila Huggie Earrings', 'laila-huggie-earrings', (select id from categories where slug = 'earrings'), 2900, null, 'Close-fit huggies for a second or third piercing. Wear them and forget them.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/laila-huggie-earrings-1.svg','/products/laila-huggie-earrings-2.svg'], 12, false, null),
  ('1720-RNG-001', 'Amber Signet Ring', 'amber-signet-ring', (select id from categories where slug = 'rings'), 3800, null, 'A classic signet shape, flat top left blank. Runs true to size.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/amber-signet-ring-1.svg','/products/amber-signet-ring-2.svg'], 19, true, 'US 5-9'),
  ('1720-RNG-002', 'Rani Stone Ring', 'rani-stone-ring', (select id from categories where slug = 'rings'), 4200, null, 'A single round-cut cubic zirconia in a retro claw setting.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/rani-stone-ring-1.svg','/products/rani-stone-ring-2.svg'], 6, true, 'US 5-9'),
  ('1720-RNG-003', 'Yasmin Band Ring', 'yasmin-band-ring', (select id from categories where slug = 'rings'), 3200, null, 'A simple, slightly domed band for stacking or wearing solo.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/yasmin-band-ring-1.svg','/products/yasmin-band-ring-2.svg'], 13, false, 'US 5-10'),
  ('1720-RNG-004', 'Dilnaz Twist Ring', 'dilnaz-twist-ring', (select id from categories where slug = 'rings'), 3600, null, 'A twisted rope band, an old motif we kept because it still works.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/dilnaz-twist-ring-1.svg','/products/dilnaz-twist-ring-2.svg'], 20, false, 'US 5-9'),
  ('1720-RNG-005', 'Sana Layer Ring', 'sana-layer-ring', (select id from categories where slug = 'rings'), 3400, null, 'Three fine bands fused into one ring, so it reads as a stack.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/sana-layer-ring-1.svg','/products/sana-layer-ring-2.svg'], 7, false, 'US 5-9'),
  ('1720-BRC-001', 'Farah Curb Chain Bracelet', 'farah-curb-chain-bracelet', (select id from categories where slug = 'bracelets'), 4400, null, 'A substantial curb chain with a lobster clasp and 2in extender.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/farah-curb-chain-bracelet-1.svg','/products/farah-curb-chain-bracelet-2.svg'], 14, true, null),
  ('1720-BRC-002', 'Alina Bangle', 'alina-bangle', (select id from categories where slug = 'bracelets'), 4800, null, 'A solid, hinged bangle. Fits most wrists 14-18cm.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/alina-bangle-1.svg','/products/alina-bangle-2.svg'], 21, true, null),
  ('1720-BRC-003', 'Nashwa Charm Bracelet', 'nashwa-charm-bracelet', (select id from categories where slug = 'bracelets'), 5200, null, 'A fine chain bracelet with three retro-shaped charms attached.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/nashwa-charm-bracelet-1.svg','/products/nashwa-charm-bracelet-2.svg'], 8, false, null),
  ('1720-BRC-004', 'Rukhsar Cuff Bracelet', 'rukhsar-cuff-bracelet', (select id from categories where slug = 'bracelets'), 5600, null, 'An open cuff with a brushed finish. One size, adjustable by hand.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/rukhsar-cuff-bracelet-1.svg','/products/rukhsar-cuff-bracelet-2.svg'], 15, false, null),
  ('1720-BRC-005', 'Mahnoor Tennis Bracelet', 'mahnoor-tennis-bracelet', (select id from categories where slug = 'bracelets'), 6200, null, 'A row of cubic zirconia stones in a low, everyday-wearable setting.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/mahnoor-tennis-bracelet-1.svg','/products/mahnoor-tennis-bracelet-2.svg'], 22, false, null),
  ('1720-NCK-001', 'Sana Chain Necklace', 'sana-chain-necklace', (select id from categories where slug = 'necklaces'), 4600, null, 'An 18in curb chain, the one piece that goes with everything.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/sana-chain-necklace-1.svg','/products/sana-chain-necklace-2.svg'], 9, true, null),
  ('1720-NCK-002', 'Roshni Pendant Necklace', 'roshni-pendant-necklace', (select id from categories where slug = 'necklaces'), 4900, null, 'A coin-shaped pendant on a fine box chain, 16-18in adjustable.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/roshni-pendant-necklace-1.svg','/products/roshni-pendant-necklace-2.svg'], 16, true, null),
  ('1720-NCK-003', 'Bela Layered Necklace', 'bela-layered-necklace', (select id from categories where slug = 'necklaces'), 5800, null, 'Two chains of different weights, pre-layered so you don''t have to.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/bela-layered-necklace-1.svg','/products/bela-layered-necklace-2.svg'], 23, false, null),
  ('1720-NCK-004', 'Anaya Choker', 'anaya-choker', (select id from categories where slug = 'necklaces'), 4400, null, 'A close-fit chain choker, 14in with a 2in extender.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/anaya-choker-1.svg','/products/anaya-choker-2.svg'], 10, false, null),
  ('1720-NCK-005', 'Meerab Coin Necklace', 'meerab-coin-necklace', (select id from categories where slug = 'necklaces'), 5200, null, 'A textured coin pendant, the kind that looks like it has a history.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/meerab-coin-necklace-1.svg','/products/meerab-coin-necklace-2.svg'], 17, false, null)
on conflict (sku) do nothing;

insert into promo_codes (code, discount_percent, active, expires_at) values
  ('WELCOME10', 10, true, null)
on conflict (code) do nothing;
