-- Replaces the placeholder demo catalog with the real product list + prices
-- (Rs 1,250-3,666, matching the locked brand guide's Rs 1,500-3,000 range
-- for the bulk of the range). Safe to run on the live database: orders
-- store a JSON snapshot of their line items (no foreign key to products),
-- and any reviews on the old placeholder products cascade-delete with them.
delete from products;

insert into products (sku, name, slug, category_id, price, compare_at_price, description, plating_spec, material_spec, images, stock_count, is_new, ring_size_range) values
  ('1720-EAR-001', 'Confetti Hoop', 'confetti-hoop', (select id from categories where slug = 'earrings'), 1974, null, 'Hoops with a scattered, mixed-texture finish along the band. Standard post-and-butterfly backs.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/confetti-hoop-1.svg','/products/confetti-hoop-2.svg'], 4, true, null),
  ('1720-EAR-002', 'Moon Drop', 'moon-drop', (select id from categories where slug = 'earrings'), 1728, null, 'A crescent-shaped drop on a fine post. Light enough for all-day wear.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/moon-drop-1.svg','/products/moon-drop-2.svg'], 11, true, null),
  ('1720-EAR-003', 'Vogue Hoop', 'vogue-hoop', (select id from categories where slug = 'earrings'), 2402, null, 'A wide, flat-profile hoop with a brushed finish. Secure hinge closure.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/vogue-hoop-1.svg','/products/vogue-hoop-2.svg'], 18, false, null),
  ('1720-EAR-004', 'Ribbon Hoop', 'ribbon-hoop', (select id from categories where slug = 'earrings'), 1352, null, 'A slim hoop with a twisted, ribbon-like silhouette. Everyday size, easy to sleep in.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/ribbon-hoop-1.svg','/products/ribbon-hoop-2.svg'], 5, false, null),
  ('1720-EAR-005', 'Cascade Drop', 'cascade-drop', (select id from categories where slug = 'earrings'), 2076, null, 'Three graduated links falling from the post for movement without extra weight.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/cascade-drop-1.svg','/products/cascade-drop-2.svg'], 12, false, null),
  ('1720-EAR-006', 'Gala Stud', 'gala-stud', (select id from categories where slug = 'earrings'), 1612, null, 'A cluster of cubic zirconia in a rounded stud setting. Secure push backs.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/gala-stud-1.svg','/products/gala-stud-2.svg'], 19, true, null),
  ('1720-EAR-007', 'Jet Hoop', 'jet-hoop', (select id from categories where slug = 'earrings'), 2216, null, 'A bold, chunky hoop with a matte-brushed texture. Hinge closure.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/jet-hoop-1.svg','/products/jet-hoop-2.svg'], 6, true, null),
  ('1720-RNG-001', 'Hammered Band', 'hammered-band', (select id from categories where slug = 'rings'), 1650, null, 'A hand-hammered texture across a simple band. Runs true to size.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/hammered-band-1.svg','/products/hammered-band-2.svg'], 13, false, 'US 5-9'),
  ('1720-RNG-002', 'Dewdrop Ring', 'dewdrop-ring', (select id from categories where slug = 'rings'), 2100, null, 'A single round-cut cubic zirconia set low on a slim band, so it sits close to the finger.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/dewdrop-ring-1.svg','/products/dewdrop-ring-2.svg'], 20, false, 'US 5-9'),
  ('1720-RNG-003', 'Confetti Band', 'confetti-band', (select id from categories where slug = 'rings'), 2340, null, 'A textured, scattered-finish band with a slight dome.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/confetti-band-1.svg','/products/confetti-band-2.svg'], 7, false, 'US 5-9'),
  ('1720-RNG-004', 'Starlet Ring', 'starlet-ring', (select id from categories where slug = 'rings'), 1810, null, 'A small star-cut cubic zirconia in a claw setting on a thin band.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/starlet-ring-1.svg','/products/starlet-ring-2.svg'], 14, true, 'US 5-9'),
  ('1720-RNG-005', 'Studded Band', 'studded-band', (select id from categories where slug = 'rings'), 1652, null, 'A row of small cubic zirconia set flush into a straight band.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/studded-band-1.svg','/products/studded-band-2.svg'], 21, true, 'US 5-9'),
  ('1720-RNG-006', 'Sculpt Ring', 'sculpt-ring', (select id from categories where slug = 'rings'), 1938, null, 'An asymmetric, sculpted band that reads as more than one ring stacked.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/sculpt-ring-1.svg','/products/sculpt-ring-2.svg'], 8, false, 'US 5-9'),
  ('1720-RNG-007', 'Whisper Band', 'whisper-band', (select id from categories where slug = 'rings'), 2476, null, 'A fine, low-profile band built to layer under or over other rings.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/whisper-band-1.svg','/products/whisper-band-2.svg'], 15, false, 'US 5-10'),
  ('1720-BRC-001', 'Trinket Cuff', 'trinket-cuff', (select id from categories where slug = 'bracelets'), 1250, null, 'An open cuff with a brushed finish. One size, adjustable by hand.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/trinket-cuff-1.svg','/products/trinket-cuff-2.svg'], 22, false, null),
  ('1720-BRC-002', 'Deco Link', 'deco-link', (select id from categories where slug = 'bracelets'), 1770, null, 'Rectangular links in a geometric, art-deco pattern. Lobster clasp with a 2in extender.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/deco-link-1.svg','/products/deco-link-2.svg'], 9, true, null),
  ('1720-BRC-003', 'Baroque Link', 'baroque-link', (select id from categories where slug = 'bracelets'), 1770, null, 'Ornate, curved links in a heavier chain. Lobster clasp with a 2in extender.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/baroque-link-1.svg','/products/baroque-link-2.svg'], 16, true, null),
  ('1720-BRC-004', 'Channel Bangle', 'channel-bangle', (select id from categories where slug = 'bracelets'), 1770, null, 'A row of cubic zirconia set into a channel along a solid, hinged bangle.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated, cubic zirconia', ARRAY['/products/channel-bangle-1.svg','/products/channel-bangle-2.svg'], 23, false, null),
  ('1720-BRC-005', 'Confetti Bangle', 'confetti-bangle', (select id from categories where slug = 'bracelets'), 3666, null, 'A textured, scattered-finish bangle, solid and hinged.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/confetti-bangle-1.svg','/products/confetti-bangle-2.svg'], 10, false, null),
  ('1720-BRC-006', 'Vine Bangle', 'vine-bangle', (select id from categories where slug = 'bracelets'), 1564, null, 'A thin, twisting vine-textured bangle. Open style, one size.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/vine-bangle-1.svg','/products/vine-bangle-2.svg'], 17, false, null),
  ('1720-NCK-001', 'Clover Pendant', 'clover-pendant', (select id from categories where slug = 'necklaces'), 1488, null, 'A four-leaf clover pendant on a fine box chain, 16-18in adjustable.', '18k gold PVD coating over 316L stainless steel', '316L stainless steel, PVD gold plated', ARRAY['/products/clover-pendant-1.svg','/products/clover-pendant-2.svg'], 4, true, null);
