// AUTO-GENERATED by scripts/generate-placeholders.mjs — do not edit by hand.
// Local fallback catalog used when Supabase env vars aren't configured yet,
// so the storefront is fully browsable before a database is wired up.
import type { Product, Category } from "@/lib/types";

export const FALLBACK_CATEGORIES: Category[] = [
  {
    "id": "earrings",
    "slug": "earrings",
    "name": "Earrings",
    "description": "Hoops, studs, and drops in PVD gold."
  },
  {
    "id": "rings",
    "slug": "rings",
    "name": "Rings",
    "description": "Signets, bands, and stone rings, true to size."
  },
  {
    "id": "bracelets",
    "slug": "bracelets",
    "name": "Bracelets",
    "description": "Chains, bangles, and cuffs built to hold up."
  },
  {
    "id": "necklaces",
    "slug": "necklaces",
    "name": "Necklaces",
    "description": "Chains and pendants for everyday layering."
  }
];

export const FALLBACK_PRODUCTS: Product[] = [
  {
    "id": "seed-001",
    "sku": "1720-EAR-001",
    "name": "Confetti Hoop",
    "slug": "confetti-hoop",
    "category_id": "earrings",
    "price": 1974,
    "compare_at_price": null,
    "description": "Hoops with a scattered, mixed-texture finish along the band. Standard post-and-butterfly backs.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/confetti-hoop-1.svg",
      "/products/confetti-hoop-2.svg"
    ],
    "stock_count": 4,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-01T00:00:00.000Z"
  },
  {
    "id": "seed-002",
    "sku": "1720-EAR-002",
    "name": "Moon Drop",
    "slug": "moon-drop",
    "category_id": "earrings",
    "price": 1728,
    "compare_at_price": null,
    "description": "A crescent-shaped drop on a fine post. Light enough for all-day wear.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/moon-drop-1.svg",
      "/products/moon-drop-2.svg"
    ],
    "stock_count": 11,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-02T00:00:00.000Z"
  },
  {
    "id": "seed-003",
    "sku": "1720-EAR-003",
    "name": "Vogue Hoop",
    "slug": "vogue-hoop",
    "category_id": "earrings",
    "price": 2402,
    "compare_at_price": null,
    "description": "A wide, flat-profile hoop with a brushed finish. Secure hinge closure.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/vogue-hoop-1.svg",
      "/products/vogue-hoop-2.svg"
    ],
    "stock_count": 18,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-03T00:00:00.000Z"
  },
  {
    "id": "seed-004",
    "sku": "1720-EAR-004",
    "name": "Ribbon Hoop",
    "slug": "ribbon-hoop",
    "category_id": "earrings",
    "price": 1352,
    "compare_at_price": null,
    "description": "A slim hoop with a twisted, ribbon-like silhouette. Everyday size, easy to sleep in.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/ribbon-hoop-1.svg",
      "/products/ribbon-hoop-2.svg"
    ],
    "stock_count": 5,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-04T00:00:00.000Z"
  },
  {
    "id": "seed-005",
    "sku": "1720-EAR-005",
    "name": "Cascade Drop",
    "slug": "cascade-drop",
    "category_id": "earrings",
    "price": 2076,
    "compare_at_price": null,
    "description": "Three graduated links falling from the post for movement without extra weight.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/cascade-drop-1.svg",
      "/products/cascade-drop-2.svg"
    ],
    "stock_count": 12,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-05T00:00:00.000Z"
  },
  {
    "id": "seed-006",
    "sku": "1720-EAR-006",
    "name": "Gala Stud",
    "slug": "gala-stud",
    "category_id": "earrings",
    "price": 1612,
    "compare_at_price": null,
    "description": "A cluster of cubic zirconia in a rounded stud setting. Secure push backs.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/gala-stud-1.svg",
      "/products/gala-stud-2.svg"
    ],
    "stock_count": 19,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-06T00:00:00.000Z"
  },
  {
    "id": "seed-007",
    "sku": "1720-EAR-007",
    "name": "Jet Hoop",
    "slug": "jet-hoop",
    "category_id": "earrings",
    "price": 2216,
    "compare_at_price": null,
    "description": "A bold, chunky hoop with a matte-brushed texture. Hinge closure.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/jet-hoop-1.svg",
      "/products/jet-hoop-2.svg"
    ],
    "stock_count": 6,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-07T00:00:00.000Z"
  },
  {
    "id": "seed-008",
    "sku": "1720-RNG-001",
    "name": "Hammered Band",
    "slug": "hammered-band",
    "category_id": "rings",
    "price": 1650,
    "compare_at_price": null,
    "description": "A hand-hammered texture across a simple band. Runs true to size.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/hammered-band-1.svg",
      "/products/hammered-band-2.svg"
    ],
    "stock_count": 13,
    "is_new": false,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-08T00:00:00.000Z"
  },
  {
    "id": "seed-009",
    "sku": "1720-RNG-002",
    "name": "Dewdrop Ring",
    "slug": "dewdrop-ring",
    "category_id": "rings",
    "price": 2100,
    "compare_at_price": null,
    "description": "A single round-cut cubic zirconia set low on a slim band, so it sits close to the finger.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/dewdrop-ring-1.svg",
      "/products/dewdrop-ring-2.svg"
    ],
    "stock_count": 20,
    "is_new": false,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-09T00:00:00.000Z"
  },
  {
    "id": "seed-010",
    "sku": "1720-RNG-003",
    "name": "Confetti Band",
    "slug": "confetti-band",
    "category_id": "rings",
    "price": 2340,
    "compare_at_price": null,
    "description": "A textured, scattered-finish band with a slight dome.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/confetti-band-1.svg",
      "/products/confetti-band-2.svg"
    ],
    "stock_count": 7,
    "is_new": false,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-10T00:00:00.000Z"
  },
  {
    "id": "seed-011",
    "sku": "1720-RNG-004",
    "name": "Starlet Ring",
    "slug": "starlet-ring",
    "category_id": "rings",
    "price": 1810,
    "compare_at_price": null,
    "description": "A small star-cut cubic zirconia in a claw setting on a thin band.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/starlet-ring-1.svg",
      "/products/starlet-ring-2.svg"
    ],
    "stock_count": 14,
    "is_new": true,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-11T00:00:00.000Z"
  },
  {
    "id": "seed-012",
    "sku": "1720-RNG-005",
    "name": "Studded Band",
    "slug": "studded-band",
    "category_id": "rings",
    "price": 1652,
    "compare_at_price": null,
    "description": "A row of small cubic zirconia set flush into a straight band.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/studded-band-1.svg",
      "/products/studded-band-2.svg"
    ],
    "stock_count": 21,
    "is_new": true,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-12T00:00:00.000Z"
  },
  {
    "id": "seed-013",
    "sku": "1720-RNG-006",
    "name": "Sculpt Ring",
    "slug": "sculpt-ring",
    "category_id": "rings",
    "price": 1938,
    "compare_at_price": null,
    "description": "An asymmetric, sculpted band that reads as more than one ring stacked.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/sculpt-ring-1.svg",
      "/products/sculpt-ring-2.svg"
    ],
    "stock_count": 8,
    "is_new": false,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-13T00:00:00.000Z"
  },
  {
    "id": "seed-014",
    "sku": "1720-RNG-007",
    "name": "Whisper Band",
    "slug": "whisper-band",
    "category_id": "rings",
    "price": 2476,
    "compare_at_price": null,
    "description": "A fine, low-profile band built to layer under or over other rings.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/whisper-band-1.svg",
      "/products/whisper-band-2.svg"
    ],
    "stock_count": 15,
    "is_new": false,
    "ring_size_range": "US 5-10",
    "created_at": "2026-07-14T00:00:00.000Z"
  },
  {
    "id": "seed-015",
    "sku": "1720-BRC-001",
    "name": "Trinket Cuff",
    "slug": "trinket-cuff",
    "category_id": "bracelets",
    "price": 1250,
    "compare_at_price": null,
    "description": "An open cuff with a brushed finish. One size, adjustable by hand.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/trinket-cuff-1.svg",
      "/products/trinket-cuff-2.svg"
    ],
    "stock_count": 22,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-15T00:00:00.000Z"
  },
  {
    "id": "seed-016",
    "sku": "1720-BRC-002",
    "name": "Deco Link",
    "slug": "deco-link",
    "category_id": "bracelets",
    "price": 1770,
    "compare_at_price": null,
    "description": "Rectangular links in a geometric, art-deco pattern. Lobster clasp with a 2in extender.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/deco-link-1.svg",
      "/products/deco-link-2.svg"
    ],
    "stock_count": 9,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-16T00:00:00.000Z"
  },
  {
    "id": "seed-017",
    "sku": "1720-BRC-003",
    "name": "Baroque Link",
    "slug": "baroque-link",
    "category_id": "bracelets",
    "price": 1770,
    "compare_at_price": null,
    "description": "Ornate, curved links in a heavier chain. Lobster clasp with a 2in extender.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/baroque-link-1.svg",
      "/products/baroque-link-2.svg"
    ],
    "stock_count": 16,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-17T00:00:00.000Z"
  },
  {
    "id": "seed-018",
    "sku": "1720-BRC-004",
    "name": "Channel Bangle",
    "slug": "channel-bangle",
    "category_id": "bracelets",
    "price": 1770,
    "compare_at_price": null,
    "description": "A row of cubic zirconia set into a channel along a solid, hinged bangle.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/channel-bangle-1.svg",
      "/products/channel-bangle-2.svg"
    ],
    "stock_count": 23,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-18T00:00:00.000Z"
  },
  {
    "id": "seed-019",
    "sku": "1720-BRC-005",
    "name": "Confetti Bangle",
    "slug": "confetti-bangle",
    "category_id": "bracelets",
    "price": 3666,
    "compare_at_price": null,
    "description": "A textured, scattered-finish bangle, solid and hinged.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/confetti-bangle-1.svg",
      "/products/confetti-bangle-2.svg"
    ],
    "stock_count": 10,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-19T00:00:00.000Z"
  },
  {
    "id": "seed-020",
    "sku": "1720-BRC-006",
    "name": "Vine Bangle",
    "slug": "vine-bangle",
    "category_id": "bracelets",
    "price": 1564,
    "compare_at_price": null,
    "description": "A thin, twisting vine-textured bangle. Open style, one size.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/vine-bangle-1.svg",
      "/products/vine-bangle-2.svg"
    ],
    "stock_count": 17,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-20T00:00:00.000Z"
  },
  {
    "id": "seed-021",
    "sku": "1720-NCK-001",
    "name": "Clover Pendant",
    "slug": "clover-pendant",
    "category_id": "necklaces",
    "price": 1488,
    "compare_at_price": null,
    "description": "A four-leaf clover pendant on a fine box chain, 16-18in adjustable.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/clover-pendant-1.svg",
      "/products/clover-pendant-2.svg"
    ],
    "stock_count": 4,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-21T00:00:00.000Z"
  }
];
