// AUTO-GENERATED by scripts/generate-placeholders.mjs — do not edit by hand.
// Local fallback catalog used when Supabase env vars aren't configured yet,
// so the storefront is fully browsable before a database is wired up.
import type { Product, Category } from "@/lib/types";

export const FALLBACK_CATEGORIES: Category[] = [
  {
    "id": "earrings",
    "slug": "earrings",
    "name": "Earrings",
    "description": "Hoops, studs, and drops in PVD gold."
  },
  {
    "id": "rings",
    "slug": "rings",
    "name": "Rings",
    "description": "Signets, bands, and stone rings, true to size."
  },
  {
    "id": "bracelets",
    "slug": "bracelets",
    "name": "Bracelets",
    "description": "Chains, bangles, and cuffs built to hold up."
  },
  {
    "id": "necklaces",
    "slug": "necklaces",
    "name": "Necklaces",
    "description": "Chains and pendants for everyday layering."
  }
];

export const FALLBACK_PRODUCTS: Product[] = [
  {
    "id": "seed-001",
    "sku": "1720-EAR-001",
    "name": "Sadaf Hoop Earrings",
    "slug": "sadaf-hoop-earrings",
    "category_id": "earrings",
    "price": 3200,
    "compare_at_price": null,
    "description": "Chunky retro hoops with a brushed finish. Everyday wear, hypoallergenic base.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/sadaf-hoop-earrings-1.svg",
      "/products/sadaf-hoop-earrings-2.svg"
    ],
    "stock_count": 4,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-01T00:00:00.000Z"
  },
  {
    "id": "seed-002",
    "sku": "1720-EAR-002",
    "name": "Noor Drop Earrings",
    "slug": "noor-drop-earrings",
    "category_id": "earrings",
    "price": 3600,
    "compare_at_price": null,
    "description": "Teardrop silhouette with a warm, retro-gold tone. Secure butterfly backs.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/noor-drop-earrings-1.svg",
      "/products/noor-drop-earrings-2.svg"
    ],
    "stock_count": 11,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-02T00:00:00.000Z"
  },
  {
    "id": "seed-003",
    "sku": "1720-EAR-003",
    "name": "Meher Stud Earrings",
    "slug": "meher-stud-earrings",
    "category_id": "earrings",
    "price": 2800,
    "compare_at_price": null,
    "description": "Cubic zirconia studs set in a low-profile PVD gold setting. Easy to layer.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/meher-stud-earrings-1.svg",
      "/products/meher-stud-earrings-2.svg"
    ],
    "stock_count": 18,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-03T00:00:00.000Z"
  },
  {
    "id": "seed-004",
    "sku": "1720-EAR-004",
    "name": "Zara Chain Earrings",
    "slug": "zara-chain-earrings",
    "category_id": "earrings",
    "price": 3400,
    "compare_at_price": null,
    "description": "Fine curb-chain drops that catch the light without being loud.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/zara-chain-earrings-1.svg",
      "/products/zara-chain-earrings-2.svg"
    ],
    "stock_count": 5,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-04T00:00:00.000Z"
  },
  {
    "id": "seed-005",
    "sku": "1720-EAR-005",
    "name": "Laila Huggie Earrings",
    "slug": "laila-huggie-earrings",
    "category_id": "earrings",
    "price": 2900,
    "compare_at_price": null,
    "description": "Close-fit huggies for a second or third piercing. Wear them and forget them.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/laila-huggie-earrings-1.svg",
      "/products/laila-huggie-earrings-2.svg"
    ],
    "stock_count": 12,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-05T00:00:00.000Z"
  },
  {
    "id": "seed-006",
    "sku": "1720-RNG-001",
    "name": "Amber Signet Ring",
    "slug": "amber-signet-ring",
    "category_id": "rings",
    "price": 3800,
    "compare_at_price": null,
    "description": "A classic signet shape, flat top left blank. Runs true to size.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/amber-signet-ring-1.svg",
      "/products/amber-signet-ring-2.svg"
    ],
    "stock_count": 19,
    "is_new": true,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-06T00:00:00.000Z"
  },
  {
    "id": "seed-007",
    "sku": "1720-RNG-002",
    "name": "Rani Stone Ring",
    "slug": "rani-stone-ring",
    "category_id": "rings",
    "price": 4200,
    "compare_at_price": null,
    "description": "A single round-cut cubic zirconia in a retro claw setting.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/rani-stone-ring-1.svg",
      "/products/rani-stone-ring-2.svg"
    ],
    "stock_count": 6,
    "is_new": true,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-07T00:00:00.000Z"
  },
  {
    "id": "seed-008",
    "sku": "1720-RNG-003",
    "name": "Yasmin Band Ring",
    "slug": "yasmin-band-ring",
    "category_id": "rings",
    "price": 3200,
    "compare_at_price": null,
    "description": "A simple, slightly domed band for stacking or wearing solo.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/yasmin-band-ring-1.svg",
      "/products/yasmin-band-ring-2.svg"
    ],
    "stock_count": 13,
    "is_new": false,
    "ring_size_range": "US 5-10",
    "created_at": "2026-07-08T00:00:00.000Z"
  },
  {
    "id": "seed-009",
    "sku": "1720-RNG-004",
    "name": "Dilnaz Twist Ring",
    "slug": "dilnaz-twist-ring",
    "category_id": "rings",
    "price": 3600,
    "compare_at_price": null,
    "description": "A twisted rope band, an old motif we kept because it still works.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/dilnaz-twist-ring-1.svg",
      "/products/dilnaz-twist-ring-2.svg"
    ],
    "stock_count": 20,
    "is_new": false,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-09T00:00:00.000Z"
  },
  {
    "id": "seed-010",
    "sku": "1720-RNG-005",
    "name": "Sana Layer Ring",
    "slug": "sana-layer-ring",
    "category_id": "rings",
    "price": 3400,
    "compare_at_price": null,
    "description": "Three fine bands fused into one ring, so it reads as a stack.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/sana-layer-ring-1.svg",
      "/products/sana-layer-ring-2.svg"
    ],
    "stock_count": 7,
    "is_new": false,
    "ring_size_range": "US 5-9",
    "created_at": "2026-07-10T00:00:00.000Z"
  },
  {
    "id": "seed-011",
    "sku": "1720-BRC-001",
    "name": "Farah Curb Chain Bracelet",
    "slug": "farah-curb-chain-bracelet",
    "category_id": "bracelets",
    "price": 4400,
    "compare_at_price": null,
    "description": "A substantial curb chain with a lobster clasp and 2in extender.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/farah-curb-chain-bracelet-1.svg",
      "/products/farah-curb-chain-bracelet-2.svg"
    ],
    "stock_count": 14,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-11T00:00:00.000Z"
  },
  {
    "id": "seed-012",
    "sku": "1720-BRC-002",
    "name": "Alina Bangle",
    "slug": "alina-bangle",
    "category_id": "bracelets",
    "price": 4800,
    "compare_at_price": null,
    "description": "A solid, hinged bangle. Fits most wrists 14-18cm.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/alina-bangle-1.svg",
      "/products/alina-bangle-2.svg"
    ],
    "stock_count": 21,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-12T00:00:00.000Z"
  },
  {
    "id": "seed-013",
    "sku": "1720-BRC-003",
    "name": "Nashwa Charm Bracelet",
    "slug": "nashwa-charm-bracelet",
    "category_id": "bracelets",
    "price": 5200,
    "compare_at_price": null,
    "description": "A fine chain bracelet with three retro-shaped charms attached.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/nashwa-charm-bracelet-1.svg",
      "/products/nashwa-charm-bracelet-2.svg"
    ],
    "stock_count": 8,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-13T00:00:00.000Z"
  },
  {
    "id": "seed-014",
    "sku": "1720-BRC-004",
    "name": "Rukhsar Cuff Bracelet",
    "slug": "rukhsar-cuff-bracelet",
    "category_id": "bracelets",
    "price": 5600,
    "compare_at_price": null,
    "description": "An open cuff with a brushed finish. One size, adjustable by hand.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/rukhsar-cuff-bracelet-1.svg",
      "/products/rukhsar-cuff-bracelet-2.svg"
    ],
    "stock_count": 15,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-14T00:00:00.000Z"
  },
  {
    "id": "seed-015",
    "sku": "1720-BRC-005",
    "name": "Mahnoor Tennis Bracelet",
    "slug": "mahnoor-tennis-bracelet",
    "category_id": "bracelets",
    "price": 6200,
    "compare_at_price": null,
    "description": "A row of cubic zirconia stones in a low, everyday-wearable setting.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated, cubic zirconia",
    "images": [
      "/products/mahnoor-tennis-bracelet-1.svg",
      "/products/mahnoor-tennis-bracelet-2.svg"
    ],
    "stock_count": 22,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-15T00:00:00.000Z"
  },
  {
    "id": "seed-016",
    "sku": "1720-NCK-001",
    "name": "Sana Chain Necklace",
    "slug": "sana-chain-necklace",
    "category_id": "necklaces",
    "price": 4600,
    "compare_at_price": null,
    "description": "An 18in curb chain, the one piece that goes with everything.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/sana-chain-necklace-1.svg",
      "/products/sana-chain-necklace-2.svg"
    ],
    "stock_count": 9,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-16T00:00:00.000Z"
  },
  {
    "id": "seed-017",
    "sku": "1720-NCK-002",
    "name": "Roshni Pendant Necklace",
    "slug": "roshni-pendant-necklace",
    "category_id": "necklaces",
    "price": 4900,
    "compare_at_price": null,
    "description": "A coin-shaped pendant on a fine box chain, 16-18in adjustable.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/roshni-pendant-necklace-1.svg",
      "/products/roshni-pendant-necklace-2.svg"
    ],
    "stock_count": 16,
    "is_new": true,
    "ring_size_range": null,
    "created_at": "2026-07-17T00:00:00.000Z"
  },
  {
    "id": "seed-018",
    "sku": "1720-NCK-003",
    "name": "Bela Layered Necklace",
    "slug": "bela-layered-necklace",
    "category_id": "necklaces",
    "price": 5800,
    "compare_at_price": null,
    "description": "Two chains of different weights, pre-layered so you don't have to.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/bela-layered-necklace-1.svg",
      "/products/bela-layered-necklace-2.svg"
    ],
    "stock_count": 23,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-18T00:00:00.000Z"
  },
  {
    "id": "seed-019",
    "sku": "1720-NCK-004",
    "name": "Anaya Choker",
    "slug": "anaya-choker",
    "category_id": "necklaces",
    "price": 4400,
    "compare_at_price": null,
    "description": "A close-fit chain choker, 14in with a 2in extender.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/anaya-choker-1.svg",
      "/products/anaya-choker-2.svg"
    ],
    "stock_count": 10,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-19T00:00:00.000Z"
  },
  {
    "id": "seed-020",
    "sku": "1720-NCK-005",
    "name": "Meerab Coin Necklace",
    "slug": "meerab-coin-necklace",
    "category_id": "necklaces",
    "price": 5200,
    "compare_at_price": null,
    "description": "A textured coin pendant, the kind that looks like it has a history.",
    "plating_spec": "18k gold PVD coating over 316L stainless steel",
    "material_spec": "316L stainless steel, PVD gold plated",
    "images": [
      "/products/meerab-coin-necklace-1.svg",
      "/products/meerab-coin-necklace-2.svg"
    ],
    "stock_count": 17,
    "is_new": false,
    "ring_size_range": null,
    "created_at": "2026-07-20T00:00:00.000Z"
  }
];
